### ISSUE TITLE
Crash when i opening .jar file

### ISSUE THREAD

**Issue by JackHarper23** [ThizThizzyDizzy/nc-reactor-generator#71] opened 2021-11-23 14:07 UTC
Hello. I have a problem, when I launch .jar file of the program, I get the error "Error in thread Initialization Thread: Unknown file format", what could be the startup problem? Thanks you for answer.

**Comment by ThizThizzyDizzy** [comment] 2021-11-23 14:33
I need a bit more information to know what the issue could be; Did it create an error log or a crash report? If not, can you run it via the command line (`java -jar path/to/filename.jar`) and send the full output?

**Comment by JackHarper23** [comment] 2021-11-23 14:37
Yes, here is crash log: [
[Error Tue Nov 23 16-13-22 EET 2021.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/7588778/Error.Tue.Nov.23.16-13-22.EET.2021.log)
](url)

**Comment by JackHarper23** [comment] 2021-11-23 14:42
https://imgur.com/a/r8K72Wr

**Comment by ThizThizzyDizzy** [comment] 2021-11-23 18:48
Hmm, it looks like it's unable to load the internal configuration, but I can't reproduce the issue on my end.
Does it get stuck on the initialization menu, or does it get to the main menu?

**Comment by JackHarper23** [comment] 2021-11-23 19:28
On the initialization menu( 
https://imgur.com/a/4hGVjfQ
If i click "Main menu" and trying import random reactor, i am seeing this: https://imgur.com/a/xJG4amm
It seems i can import NCPF format and export it on JSON, but i don't know how it will work in the game, in Reactor Builder.

**Comment by ThizThizzyDizzy** [comment] 2021-11-24 14:26
If you go to the settings menu and click the load nuclearcraft configuration button, does it do the same thing?

I don't think this would be a Java version issue, but you can always try updating Java

**Comment by JackHarper23** [comment] 2021-11-25 06:53
I loaded the nuclearcraft configuration  as you said and it loaded, tried to load the reactor - nothing crashed. I close NC generator and open it again - same crash, but if i load configuration manually - it works and i can use program! Thank you so much!!

**Comment by ThizThizzyDizzy** [comment] 2022-02-28 21:48
(Probably) Fixed in v4.0

**Closed by ThizThizzyDizzy** 2022-02-28 21:48 UTC
Labels: bug, Fixed in Dev, unable to reproduce
