### ISSUE TITLE
Error with placing heat sinks and zooming

### ISSUE THREAD

**Issue by player19375** [ThizThizzyDizzy/nc-reactor-generator#42] opened 2021-04-30 12:00 UTC
[Error Fri Apr 30 19-15-09 GMT+08-00 2021.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6405103/Error.Fri.Apr.30.19-15-09.GMT%2B08-00.2021.log)
Under a quite specific combination of keys, the planner gives an error. 
To reproduce the error:
1. Open a relatively complex design (any 9^3 reactor or larger should do)
2. Select box tool
3. Pick a heat sink that can be placed in the reactor (or remove a random heat sink to add it back)
4. Hold control and drag along the reactor.
5. An error is shown when you scroll.

**Comment by ThizThizzyDizzy** [comment] 2021-04-30 16:40
Duplicate of #41

**Closed as completed by ThizThizzyDizzy** 2021-04-30 16:40 UTC
